version: '3.7'

services:
  web:
    build: .
    environment:
      DEBUG: "${DEBUG}"
      DATABASE_URL: "${DATABASE_URL}"
      PORT: "${PORT}"
      REDIS_URL: "${REDIS_URL}"
      SERVERNAMES: "${SERVERNAMES}"
    volumes:
      - .:/app
      - ~/mediafiles:/app/mediafiles
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis
    links:
      - redis

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  rq:
    build: .
    command: ./compose/run_rq.sh
    environment:
      DEBUG: "${DEBUG}"
      DATABASE_URL: "${DATABASE_URL}"
      PORT: "${PORT}"
      REDIS_URL: "${REDIS_URL}"
      SERVERNAMES: "${SERVERNAMES}"
    links:
      - redis
    depends_on:
      - db
      - redis

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_PORT_NUMBER: ${REDIS_PORT_NUMBER}
    ports:
      - ${REDIS_PORT_NUMBER}:${REDIS_PORT_NUMBER}

volumes:
  pgdata:
