# Generated by Django 3.2 on 2021-04-27 21:08

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.CharField(choices=[('-1', 'Everyone'), ('-2', 'Class'), ('-3', 'Race'), ('-4', 'Cabal'), ('-5', 'Psalm')], default='-1', max_length=2)),
                ('restriction_type', models.CharField(max_length=255)),
                ('keywords_main', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('syntax', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('description', models.CharField(max_length=255)),
                ('see_also', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
        ),
    ]
