# Generated by Django 3.2 on 2021-05-27 06:32

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parseradmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='keywords_main',
        ),
        migrations.AddField(
            model_name='entry',
            name='keyword_main',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='keywords',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='restriction',
            field=models.CharField(choices=[('-1', 'Everyone'), ('-2', 'Class'), ('-3', 'Race'), ('-4', 'Cabal'), ('-5', 'Psalm'), ('51', 'Level51'), ('52', 'Level52'), ('53', 'Level53'), ('54', 'Level54'), ('55', 'Level55'), ('56', 'Level56'), ('57', 'Level57'), ('58', 'Level58'), ('59', 'Level59'), ('60', 'Level60')], default='-1', max_length=2),
        ),
        migrations.AlterField(
            model_name='entry',
            name='restriction_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='see_also',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='syntax',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
