# Generated by Django 3.2 on 2021-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseradmin', '0004_alter_entry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
