# Generated by Django 3.2 on 2021-05-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parseradmin', '0005_entry_raw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
