# Generated by Django 3.2 on 2021-05-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseradmin', '0006_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('keyword_main',), 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='keyword_main',
            field=models.CharField(max_length=255),
        ),
    ]
