# Generated by Django 3.2 on 2021-05-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseradmin', '0007_auto_20210531_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='keyword_main',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
