# Generated by Django 3.2 on 2021-06-01 06:49

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parseradmin', '0008_alter_entry_keyword_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='keywords',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200, unique=True), blank=True, null=True, size=None),
        ),
    ]
