# Generated by Django 3.2 on 2021-06-01 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parseradmin', '0009_alter_entry_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('restriction', models.CharField(choices=[('-1', 'Everyone'), ('-2', 'Class'), ('-3', 'Race'), ('-4', 'Cabal'), ('-5', 'Psalm'), ('51', 'Level51'), ('52', 'Level52'), ('53', 'Level53'), ('54', 'Level54'), ('55', 'Level55'), ('56', 'Level56'), ('57', 'Level57'), ('58', 'Level58'), ('59', 'Level59'), ('60', 'Level60')], default='-1', max_length=2)),
                ('restriction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword_main', models.CharField(db_index=True, max_length=255)),
                ('keywords', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200, unique=True), blank=True, null=True, size=None)),
                ('syntax', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('see_also', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('raw', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical entry',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
