# Generated by Django 3.2 on 2021-06-03 05:58

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parseradmin', '0010_historicalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='keywords',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200, unique=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='see_also',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='syntax',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='keywords',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200, unique=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='see_also',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='syntax',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
    ]
