# Generated by Django 3.2 on 2021-06-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parseradmin', '0013_auto_20210603_0604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('keyword_main',), 'permissions': [('can_import_entries', 'Can Import Entries'), ('can_export_entries', 'Can Export Entries')], 'verbose_name_plural': 'Entries'},
        ),
    ]
